spring:
  application:
    name: vem-pro-culto-api
    auth_app: ajudaqui-ms

  datasource:
    # url: jdbc:postgresql://127.0.0.1:5432/vem_pro_culto
    url: jdbc:postgresql://localhost/vpc_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false # colocar como false deposi paga esconder os logs do banco
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8084

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
